# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnalyzeSDWebImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AnalyzeSDWebImage

  pod 'SDWebImage', '~> 3.7.6'

  target 'AnalyzeSDWebImageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnalyzeSDWebImageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
