# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnalyzePromiseKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  pod "PromiseKit", "~> 1.6"
  # Pods for AnalyzePromiseKit

  target 'AnalyzePromiseKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnalyzePromiseKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
